configuration:
  swagger:
    app: 'Recipe Sharing App'
    description: 'A simple recipe sharing app built with Spring Boot'
    developer: 'Arnela Ombasa'
    email: 'arnela.ombasa@ibu.edu.ba'
  mailsender:
    default: 'sendgrid'

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: food
security:
  jwt:
    secret: 'mXLjT3Gm4skNsCdntWodbHPb1GqY35fGVaisLwImIp8cLZP7W6'
