configuration:
  swagger:
    app: 'Recipe Sharing App'
    description: 'A simple recipe sharing app built with Spring Boot'
    developer: 'Arnela Ombasa'
    email: 'arnela.ombasa@ibu.edu.ba'
  mailsender:
    default: 'sendgrid'

spring:
  data:
    mongodb:
      uri: mongodb+srv://arnelaomb:hSj8up2bp5BBCSkD@cluster0.xaqsyrk.mongodb.net/?retryWrites=true&w=majority
      database: recipes
security:
  jwt:
    secret: 'mXLjT3Gm4skNsCdntWodbHPb1GqY35fGVaisLwImIp8cLZP7W6'
